import { LogoWhiteRound as LogoWhite } from "../../../assets/images/new";


export const stakingList1 = [
    {
        name: 'CAPO',
        apy: '10%',
        stakingCap: '40,000,000 SIN',
        lock: '6 months',
        startDate: '15 July 2024',
        guideLink: 'https://medium.com/@TheSinVerse/introducing-the-new-sinverse-staking-program-loyalty-is-rewarded-209ce20760a7',
        stakingLink: 'https://sinverse.com/capo',
        image: LogoWhite,
        closed: false,
        hideAction: false,
        exemption: true,
    },
    {
        name: 'UNDERBOSS',
        apy: '51%',
        stakingCap: '20,000,000 SIN',
        lock: '9 Months',
        startDate: '15 July 2024',
        guideLink: 'https://medium.com/@TheSinVerse/introducing-the-new-sinverse-staking-program-loyalty-is-rewarded-209ce20760a7',
        stakingLink: 'https://sinverse.com/underboss',
        image: LogoWhite,
        closed: false,
        hideAction: false,
        exemption: true,
    },
    {
        name: 'KINGPIN',
        apy: '25%',
        stakingCap: '10,000,000 SIN',
        lock: '12 Months',
        startDate: '15 July 2024',
        guideLink: 'https://medium.com/@TheSinVerse/introducing-the-new-sinverse-staking-program-loyalty-is-rewarded-209ce20760a7',
        stakingLink: 'https://sinverse.com/kingpin',
        image: LogoWhite,
        closed: false,
        hideAction: false,
        exemption: true,
    },
];
export const stakingList2 = [
    {
        name: 'Premium Staking pool',
        apy: '50%',
        stakingCap: '10,000,000 $SIN',
        stakingPeriod: '6 Months',
        startDate: '5 May 2023',
        guideLink: 'https://medium.com/@TheSinVerse/business-license-staking-pools-go-live-at-9pm-utc-5-may-2023-whitelist-opportunities-c3cdeb9677e6',
        stakingLink: 'https://sinverse.com/premiumstake/',
        full: true,
        hideAction: false,
        image: LogoWhite,
        exemption: false,
    },
    {
        name: 'Exclusive Staking pool',
        apy: '50%',
        stakingCap: '10,000,000 $SIN',
        stakingPeriod: '6 Months',
        startDate: '5 May 2023',
        guideLink: 'https://medium.com/@TheSinVerse/business-license-staking-pools-go-live-at-9pm-utc-5-may-2023-whitelist-opportunities-c3cdeb9677e6',
        stakingLink: 'https://sinverse.com/exclusivestake/',
        full: true,
        hideAction: false,
        image: LogoWhite,
        exemption: false,
    },
];