import { LogoWhiteRound as LogoWhite } from "../../../assets/images/new";


export const stakingList1 = [
    {
        name: 'OG STAKING',
        apy: '50%',
        stakingCap: '25,000,000 SIN',
        lock: '6 months',
        startDate: '16 July 2023',
        guideLink: 'https://medium.com/@TheSinVerse/og-staking-pool-v2-all-the-details-3a181409f7df',
        stakingLink: 'https://sinverse.com/ogstakingv2/',
        image: LogoWhite,
        closed: true,
        hideAction: false,
        exemption: true,
    },
    {
        name: 'LAND V3 STAKING',
        apy: '50%',
        stakingCap: '20,000,000 SIN',
        lock: '6 Months',
        startDate: '15th January 2023',
        guideLink: 'https://medium.com/@TheSinVerse/get-ahead-of-the-game-stake-your-sin-tokens-and-secure-a-whitelist-opportunity-for-valuable-land-18666573d966',
        stakingLink: 'https://sinverse.com/stakingv3',
        image: LogoWhite,
        closed: true,
        hideAction: false,
        exemption: true,
    },
    {
        name: 'LAST CHANCE SALOON',
        apy: '50%',
        stakingCap: '10,000,000 SIN',
        lock: '6 Months',
        startDate: '24th January 2023',
        guideLink: 'https://medium.com/@TheSinVerse/last-chance-saloon-your-last-chance-to-stake-sin-and-secure-a-whitelist-opportunity-for-the-v3-a155786a58c3',
        stakingLink: 'https://sinverse.com/stakingv4',
        image: LogoWhite,
        closed: true,
        hideAction: false,
        exemption: true,
    },
];
export const stakingList2 = [
    {
        name: 'Premium Staking pool',
        apy: '50%',
        stakingCap: '10,000,000 $SIN',
        stakingPeriod: '6 Months',
        startDate: '5 May 2023',
        guideLink: 'https://medium.com/@TheSinVerse/business-license-staking-pools-go-live-at-9pm-utc-5-may-2023-whitelist-opportunities-c3cdeb9677e6',
        stakingLink: 'https://sinverse.com/premiumstake/',
        full: true,
        hideAction: false,
        image: LogoWhite,
        exemption: false,
    },
    {
        name: 'Exclusive Staking pool',
        apy: '50%',
        stakingCap: '10,000,000 $SIN',
        stakingPeriod: '6 Months',
        startDate: '5 May 2023',
        guideLink: 'https://medium.com/@TheSinVerse/business-license-staking-pools-go-live-at-9pm-utc-5-may-2023-whitelist-opportunities-c3cdeb9677e6',
        stakingLink: 'https://sinverse.com/exclusivestake/',
        full: true,
        hideAction: false,
        image: LogoWhite,
        exemption: false,
    },
];