import { LogoWhiteRound as LogoWhite } from "../../../assets/images/new";


export const stakingList1 = [
    {
        name: 'LICENSE STAKING',
        apy: '25%',
        stakingCap: '10,000,000 SIN',
        lock: '6 Months',
        endDate: '5th May 2023',
        guideLink: 'https://medium.com/@TheSinVerse/sinverse-og-staking-pools-60ca5fe272c',
        stakingLink: 'https://sinverse.com/ogstaking/',
        image: LogoWhite,
        closed: true,
        hideAction: true,
    },
    {
        name: 'LAND V3 STAKING',
        apy: '50%',
        stakingCap: '20,000,000 SIN',
        lock: '6 Months',
        endDate: '15th January 2023',
        guideLink: 'https://medium.com/@TheSinVerse/get-ahead-of-the-game-stake-your-sin-tokens-and-secure-a-whitelist-opportunity-for-valuable-land-18666573d966',
        stakingLink: 'https://sinverse.com/stakingv3',
        image: LogoWhite,
        closed: true,
    },
    {
        name: 'LAST CHANCE SALOON',
        apy: '50%',
        stakingCap: '10,000,000 SIN',
        lock: '6 Months',
        endDate: '24th January 2023',
        guideLink: 'https://medium.com/@TheSinVerse/last-chance-saloon-your-last-chance-to-stake-sin-and-secure-a-whitelist-opportunity-for-the-v3-a155786a58c3',
        stakingLink: 'https://sinverse.com/stakingv4',
        image: LogoWhite,
        closed: true,
    },
];
export const stakingList2 = [
    {
        name: 'Premium Staking pool',
        apy: '25%',
        stakingCap: '10, 000,000 $SIN',
        stakingPeriod: '6 Months',
        startDate: '5 May 9pm UTC',
        guideLink: 'https://medium.com/@TheSinVerse/business-license-staking-pools-go-live-at-9pm-utc-5-may-2023-whitelist-opportunities-c3cdeb9677e6',
        stakingLink: 'https://sinverse.com/premiumstake/',
        full: false,
        hideAction: false,
        image: LogoWhite,
    },
    {
        name: 'Exclusive Staking pool',
        apy: '25%',
        stakingCap: '10, 000,000 $SIN',
        stakingPeriod: '6 Months',
        startDate: '5 May 9pm UTC',
        guideLink: 'https://medium.com/@TheSinVerse/business-license-staking-pools-go-live-at-9pm-utc-5-may-2023-whitelist-opportunities-c3cdeb9677e6',
        stakingLink: 'https://sinverse.com/exclusivestake/',
        full: false,
        hideAction: false,
        image: LogoWhite,
    },
];