 
 
 export const routeConstants = {
     all: '*',
     home: '/',
     home2: 'home',
     about: 'about',
     userLogin: 'log-in',
     register: 'register',
     privacyPolicy: 'privacy-policy',
     terms: 'terms',
     amlPolicy: 'aml-policy',
     faq: 'faq',
     help: 'help',
     learn: 'learn',
     productUpdates: 'product-updates',
     careers: 'careers',
     contact: 'contact-us',
     operators: 'operators',
     placeHolder: 'waiting',
     cryptoCurrencies: 'crypto-currencies',
     manillaCard: 'card',
     manillaToken: 'token',
     imageResources: 'image-resources',

     exchange: 'exchange',
     industryNews: 'news',
     token: 'token',
     documents: 'documents',
     download: 'download',
     gameInfo: 'game-info',
     staking: 'staking',
     districtReveal: 'district-reveal',

     admin: 'admin',
     dashboard: 'dashboard',
     adminRegister: 'register',
     adminLogin: 'log-in',
     adminStatistics: 'stats',
     adminPosts: 'posts',
     adminLearn: 'learn-posts',
     adminWaitlistMessages: 'waitlist-messages',
     adminVisitorMessages: 'visitor-messages',
 };